In [484]:
import ARS_main
import History_Manager
import Collect_Direction
import Construct_Model
import Solve_TR
from ARS_main import ARS
import numpy as np
# reload ARS using importlib.reload
import importlib
importlib.reload(ARS_main)
importlib.reload(History_Manager)
importlib.reload(Collect_Direction)
importlib.reload(Construct_Model)
importlib.reload(Solve_TR)

<module 'Solve_TR' from 'c:\\Users\\Lenovo\\Desktop\\新建文件夹\\Blackbox_Solver-main\\Blackbox_Solver-main\\Solve_TR.py'>

In [485]:
x0=[0.,0.,1.,1]
def obj_fun(x):
    return x[0]**2+x[1]**2+x[2]**2+x[3]**2
prob = ARS(x0,obj_fun,None,None,None)

In [486]:
a,b = prob.ARS_run()

[[1.15320879 2.75049475 2.32615264 1.8530471 ]]
[[ 1.          1.          1.          1.        ]
 [-4.01432972 -0.56353367 -0.97869343 -1.7621091 ]]
[[-0.97034591 -0.49094517 -0.69945211 -0.86971049]
 [-0.69370234 -1.51303893  2.3595077   2.99665501]]
[[-3.75984325e-07 -1.91589650e-06 -2.75678575e-07  1.17118854e-06]
 [-6.92760715e-01 -1.27756825e+00  5.88655326e-01 -4.10841039e-01]]
[[-2.17093330e-06 -5.99857268e-06 -1.87327668e-06  1.14028389e-05]
 [ 6.69317686e-01 -1.67112079e+00  2.05916802e+00  1.05469055e+00]]
[[-2.59480165e-05 -2.87164051e-05 -7.27780023e-06  8.64923942e-05]
 [ 1.97251540e-02 -6.77315870e-01  1.43926747e+00  6.78677793e-01]]
[[-2.10476382e-02 -6.78357767e-04 -8.09056038e-05  2.03907997e-03]
 [-5.28385126e-01 -9.53791360e-01  3.64725556e-01  4.21084741e+00]]
[[ 8.28588224e-07  1.30127467e-07  4.68907101e-07  1.52692815e-06]
 [ 1.58758139e-01 -1.05952093e+00  7.24021212e-01 -4.52254852e-01]]
[[ 8.35069727e-05  1.96507632e-06  1.03622843e-05  5.40200958e-05]
 [ 9

In [487]:
a

{'solution': array([ 0.02403036,  0.02613881,  0.04069538, -0.0415872 ]),
 'Objective': 0.00464630506588853,
 'niter': 31,
 'nfev': 216,
 'ngrad': 0,
 'status': 1,
 'fhist': [2.0,
  2.0,
  1.5056457672230543,
  1.5056421427946294,
  1.5056186932598696,
  1.505447663966431,
  1.5005243673374076,
  1.500521208371711,
  1.5004164187825892,
  1.4992475597713044,
  1.4980661756200386,
  1.4980635183797064,
  1.4980526082058518,
  1.497923658827134,
  1.4954508892751734,
  1.004619437800126,
  1.0046175924880931,
  1.0045866030450434,
  1.0016937336719676,
  0.9677084557464499,
  0.8257937593174866,
  0.792104263396167,
  0.7921025255991311,
  0.792098890045326,
  0.7920951284631379,
  0.6586632379795152,
  0.6586613956693077,
  0.06398519711372536,
  0.039934069074533105,
  0.02646555324207637,
  0.004646450996928314,
  0.00464630506588853]}

In [488]:
b.total_history
#b.iter_history

{(0,
  'EG'): {'point': array([[ 1.49302449e-06,  1.60845689e-06,  1.00000103e+00,
           1.00000119e+00],
         [ 1.49302449e-06,  1.60845689e-06,  1.00000103e+00,
           1.00000119e+00],
         [ 1.41300574e-06, -1.35873520e-06,  1.00000001e+00,
           1.00000019e+00],
         [ 1.41300574e-06, -1.35873520e-06,  1.00000001e+00,
           1.00000019e+00],
         [-6.45481039e-07,  1.24907652e-06,  1.00000120e+00,
           1.00000063e+00],
         [-6.45481039e-07,  1.24907652e-06,  1.00000120e+00,
           1.00000063e+00],
         [-5.88726613e-07, -3.65755182e-07,  1.00000085e+00,
           9.99999358e-01],
         [-5.88726613e-07, -3.65755182e-07,  1.00000085e+00,
           9.99999358e-01]]), 'objective': array([2.00000444, 2.00000444, 2.00000041, 2.00000041, 2.00000366,
         2.00000366, 2.00000041, 2.00000041]), 'stage': 'EG'},
 (0, 'CM'): {'point': array([[-1., -1.,  0.,  0.]]),
  'objective': array([2.]),
  'stage': 'CM'},
 (0,
  'TR'): {'point'