In [382]:
import ARS_main
import History_Manager
import Collect_Direction
import Construct_Model
import Solve_TR
from ARS_main import ARS
import numpy as np
# reload ARS using importlib.reload
import importlib
importlib.reload(ARS_main)
importlib.reload(History_Manager)
importlib.reload(Collect_Direction)
importlib.reload(Construct_Model)
importlib.reload(Solve_TR)

<module 'Solve_TR' from 'c:\\Users\\Lenovo\\Desktop\\新建文件夹\\Blackbox_Solver-main\\Blackbox_Solver-main\\Solve_TR.py'>

In [383]:
x0=[0.,0.,1.,1]
def obj_fun(x):
    return x[0]**2+x[1]**2+x[2]**2
prob = ARS(x0,obj_fun,None,None,None)

In [384]:
a,b = prob.ARS_run()

[[-0.5820918   0.10709065  0.6177814  -0.0482813 ]
 [-0.31680724 -0.36030373  2.52539187  0.44977577]
 [-1.24282653  1.20525397  4.04439122 -0.939004  ]
 [ 0.30215554 -0.82292387 -0.4545321  -0.15779383]
 [ 0.41848981  0.8677134  -0.19411139 -0.18509594]
 [-0.70988863 -0.222277    0.57205107 -0.34555555]]
[[ 1.77175049  1.11992116  4.02359849  0.73541098]
 [ 0.04510577 -0.12098578  0.16912435 -0.22491911]
 [ 0.25561923  0.36321825  1.12733935 -0.83111628]
 [ 0.90621192  0.07302025  0.38365092  0.16204929]
 [ 0.2147818   0.67147743  0.65006406 -0.28355519]
 [-0.52293667 -0.28448019  0.80211515 -0.047112  ]]
[[ 8.46340018e-07  1.40783196e-06  2.21266925e-06 -2.33523159e-07]
 [-3.07302645e-01  1.12100537e+00  2.20866786e+00  7.14083728e-02]
 [-1.03305135e+00  1.12373289e+00  4.56158299e+00 -2.95882012e-01]
 [ 2.39628835e-02  8.44584616e-01  2.59340041e+00 -3.02965941e+00]
 [ 4.87078548e-01 -4.84911885e-01  1.91320496e-01 -7.00722070e-01]
 [-3.74523891e-01 -3.73698220e-01  8.00831465e-01  

In [362]:
a

{'solution': array([1.50091030e-03, 1.06498036e-03, 7.21283004e-04, 1.35978030e+00]),
 'Objective': 3.907164061461257e-06,
 'niter': 50,
 'nfev': 4751,
 'ngrad': 0,
 'status': 1,
 'fhist': [0.7511162432250464,
  0.7511137048283654,
  0.5802868539138551,
  0.5719444115097089,
  0.5719352327112671,
  0.5498421725689301,
  0.5498251869424947,
  0.5277673083612358,
  0.5276175125375165,
  0.5272588947253044,
  0.5247031708132167,
  0.5154060150422514,
  0.5132787496575798,
  0.5057034933013362,
  0.48214700916183456,
  0.4809797231845858,
  0.48053327585023026,
  0.4766632317729944,
  0.47040415362644766,
  0.466609764760981,
  0.4561899720085082,
  0.45237936324979233,
  0.4458645071534362,
  0.4413640984166342,
  0.4307424256870453,
  0.4214502621320241,
  0.38424507944506875,
  0.37994354459332774,
  0.371505562393946,
  0.3617657741725658,
  0.3477137413953619,
  0.33579288651790745,
  0.3299534352083428,
  0.21709675769166156,
  0.2154880554614258,
  0.16829164898116117,
  0.065412390

In [385]:
b.total_history[0,'EG']
b.iter_history

{0: {'point': array([ 0.04551701, -0.11735072,  0.97665244,  0.96492502]),
  'objective': 0.9696929810194718,
  'stage': 'CM'},
 1: {'point': array([ 0.04551616, -0.11735213,  0.97665023,  0.96492525]),
  'objective': 0.9696889123838868,
  'stage': 'EG'},
 2: {'point': array([ 0.04551575, -0.1173515 ,  0.97664807,  0.96492554]),
  'objective': 0.9696845110718976,
  'stage': 'EG'},
 3: {'point': array([ 0.19535839, -0.10578917,  0.91592169,  0.96309819]),
  'objective': 0.8882687895187374,
  'stage': 'CM'},
 4: {'point': array([-0.01703786,  0.03851604,  0.8785136 ,  1.05773412]),
  'objective': 0.7735599252837364,
  'stage': 'CM'},
 5: {'point': array([0.07020143, 0.03678792, 0.82926481, 1.17580672]),
  'objective': 0.6939617240164577,
  'stage': 'CM'},
 6: {'point': array([0.14567184, 0.08180294, 0.80637941, 1.18609059]),
  'objective': 0.6781597607133237,
  'stage': 'CM'},
 7: {'point': array([ 0.03143217, -0.05127001,  0.78309462,  1.13204575]),
  'objective': 0.6168537795044589,
  